default: &default
  adapter: postgresql
  encoding: unicode
  username: kaa
  password: "123456"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: payments_development

test:
  <<: *default
  database: payments_test
